src/Workleap.DomainEventPropagation.Abstractions/IDomainEvent.cs
src/Workleap.DomainEventPropagation.Abstractions/ITopicProvider.cs
src/Workleap.DomainEventPropagation.Abstractions/PublicApi.Shipped.txt
src/Workleap.DomainEventPropagation.Abstractions/PublicApi.Unshipped.txt
src/Workleap.DomainEventPropagation.Abstractions/Workleap.DomainEventPropagation.Abstractions.csproj
src/Workleap.DomainEventPropagation.sln

Port over the original abstractions project, but with minor tweaks to retrofit with our current solution:
- Use the same namespace as the main package
- Added support for assembly signage with the same `.snk` key as the main package
- Include symbols as `snupkg`
- Link to the main package's `README`
- Use public API analyzers:
-  Disable the current warnings for the time being, until the code has been stabilized across the board
- Make internal types visible to the tests project and `DynamicProxyGenAssembly2` (e.g. for Moq)

[IDP-433] port abstractions project

---

src/Workleap.DomainEventPropagation.Publishing/EventPropagationClient.cs
src/Workleap.DomainEventPropagation.Publishing/EventPropagationPublisherOptions.cs
src/Workleap.DomainEventPropagation.Publishing/Extensions/ServiceCollectionExtensions.cs
src/Workleap.DomainEventPropagation.Publishing/Workleap.DomainEventPropagation.Publishing.csproj
src/Workleap.DomainEventPropagation.Tests/Publishing/EventPropagationClientTests.cs
src/Workleap.DomainEventPropagation.Tests/Publishing/EventPropagationPublisherOptionsTests.cs
src/Workleap.DomainEventPropagation.Tests/Workleap.DomainEventPropagation.Tests.csproj

Refactor out the `EventGridPublisherClient` configuration from the event propagation client into the dependency injection registration by leveraging `Microsoft.Azure.Extensions`' extension methods
Install and use `FakeItEasy` for related unit tests

[IDP-453] feat(refactor): Event Grid publisher client setup

---

src/Workleap.DomainEventPropagation.Publishing/EventPropagationPublisherOptions.cs
src/Workleap.DomainEventPropagation.Publishing/Extensions/ServiceCollectionEventPropagationExtensions.cs
src/Workleap.DomainEventPropagation.Tests/Publishing/ServiceCollectionEventPropagationExtensionsTests.cs

As discussed, I modified the AddAzureClients a bit so we'll make use of factories in order not to materialize options halfway through our registrations.
I also checked and the factory will only be called once since ClientRegistration keeps a cache of the created client. ClientRegistration is the internal class that ultimately receives our client factory and will invoke it if it hasn't been done before.
Also added a couple of registration tests.

IDP-514 - Lazily load publisher options in our registration method

---

src/Workleap.DomainEventPropagation.Publishing/EventPropagationClient.cs
src/Workleap.DomainEventPropagation.Subscription/DomainEventGridWebhookHandler.cs
src/Workleap.DomainEventPropagation.Tests/Subscription/DomainEventGridWebhookHandlerTests.cs
src/Workleap.DomainEventPropagation.Tests/Subscription/Events/EventsApiIntegrationTests.cs
src/Workleap.DomainEventPropagation.sln

The current library we started off would scan assemblies with a hardoded name filter in order to retrieve the domain event type. It works in that team's usecase but not when applied to any team. So we needed to change that to be more flexible while also not scanning all the Microsoft assemblies.
Turns out we control the info sent with the event and when we get the Type of event in the publisher package we can use AssemblyQualifiedName instead of FullName currently. AssemblyQualifiedName contains the full namespace but also which assembly it comes from. Using this makes it simpler afterwards to retrieve the Type in the subscriber package.
- Use AssemblyQualifiedName instead of FullName in the subscriber library when creating the EventGridEvent in EventPropagationClient
- Use Type.GetType …

IDP-513 Improve assembly scanning by filtering

---

src/Workleap.DomainEventPropagation.Tests/Publishing/EventPropagationPublisherOptionsValidatorTests.cs
src/Workleap.DomainEventPropagation.Tests/Subscription/EventGridRequestHandlerTests.cs
src/Workleap.DomainEventPropagation.Tests/Subscription/SubscriptionEventWebhookHandlerTests.cs
src/Workleap.DomainEventPropagation.Tests/Workleap.DomainEventPropagation.Tests.csproj

In order to keep our libs unified, we want all of them to use FakeItEasy. So we need to change the remaining tests that use moq.
- Removed moq package from our test project
- Adjusted EventGridRequestHandlerTests to use FakeItEasy instead of moq

IDP-527 - Remove moq

---

src/Workleap.DomainEventPropagation.Abstractions/IDomainEvent.cs
src/Workleap.DomainEventPropagation.Abstractions/PublicAPI.Unshipped.txt
src/Workleap.DomainEventPropagation.Publishing/EventPropagationClient.cs
src/Workleap.DomainEventPropagation.Tests/Publishing/EventPropagationClientTests.cs

As an IDP developer I want to remove any unnecessary field on public facing api so that devs are not confused.
We need to remove the DataVersion field on IDomainEvent interface, we talked with Julien and it’s not something that is used. We should just hardcode version 1.0 on events.
- DataVersion was removed from IDomainEvent
- DataVersion was HardConded using a string constant with value 1.0
- Test was added to validate that all events are versio 1.0

IDP-536 - Remove DataVersion field

---

src/Workleap.DomainEventPropagation.Publishing/EventPropagationPublisherOptions.cs
src/Workleap.DomainEventPropagation.Publishing/EventPropagationPublisherOptionsValidator.cs
src/Workleap.DomainEventPropagation.Publishing/Extensions/ServiceCollectionEventPropagationExtensions.cs
src/Workleap.DomainEventPropagation.Publishing/Workleap.DomainEventPropagation.Publishing.csproj
src/Workleap.DomainEventPropagation.Subscription/Workleap.DomainEventPropagation.Subscription.csproj
src/Workleap.DomainEventPropagation.Tests/Publishing/EventPropagationPublisherOptionsTests.cs
src/Workleap.DomainEventPropagation.Tests/Publishing/EventPropagationPublisherOptionsValidatorTests.cs

As an IDP developer I want to have an unambiguous library.
Currently in the EventPropagation library, more specifically in the EventPropagationPublisherOptions class we have validation attributes on certain properties and also a validator class. It’s not a bad thing, but we could pick one or the other. We’ll pick to keep the validator class since what’s in there cannot be reproduced with the current attributes we have.
- Move attributes validation from EventPropagationPublisherOptions to EventPropagationPublisherOptionsValidator
- Copy tests from EventPropagationPublisherOptionsTests to EventPropagationPublisherOptionsValidatorTests. Original tests were kept because they are validated through the service creation itself.
- ValidateDataAnnotation is removed from our extension method
- …

IDP-528 - Remove options validation attributes

---

src/Shared/InMemoryActivityTracker.cs
src/Shared/TelemetryClientExtensions.cs
src/Shared/TracingHelper.cs
src/Workleap.DomainEventPropagation.Publishing.ApplicationInsights/ApplicationInsightsPublishingDomainEventBehavior.cs
src/Workleap.DomainEventPropagation.Publishing.Tests/TracingBehaviorTests.cs
src/Workleap.DomainEventPropagation.Publishing/TracingPublishingDomainEventBehavior.cs
src/Workleap.DomainEventPropagation.Subscription.ApplicationInsights/ApplicationInsightsSubscriptionDomainEventBehavior.cs
src/Workleap.DomainEventPropagation.Subscription.Tests/SampleDomainEvent.cs
src/Workleap.DomainEventPropagation.Subscription.Tests/TracingBehaviorTests.cs
src/Workleap.DomainEventPropagation.Subscription/TracingSubscriptionDomainEventBehavior.cs

Given the cloud events [convention](https://github.com/open-telemetry/semantic-conventions/blob/main/docs/cloudevents/cloudevents-spans.md#conventions), we want to have the event type exposed in an activity name. 
- Modified the otel behaviors to display the event type name
- Modified the app insights behaviors to display the event type name

IDP-573 - Change activity display name

---

.github/workflows/ci.yml
src/Shared/DomainEventWrapper.cs
src/Shared/DomainEventWrapperCollection.cs
src/Workleap.DomainEventPropagation.Abstractions/DomainEventAttribute.cs
src/Workleap.DomainEventPropagation.Abstractions/DomainEventSchemaCache.cs
src/Workleap.DomainEventPropagation.Abstractions/EventSchema.cs
src/Workleap.DomainEventPropagation.Abstractions/PublicAPI.Shipped.txt
src/Workleap.DomainEventPropagation.Abstractions/PublicAPI.Unshipped.txt
src/Workleap.DomainEventPropagation.Publishing.Tests/DomainEventSchemaCacheTests.cs
src/Workleap.DomainEventPropagation.Publishing.Tests/DomainEventWrapperTests.cs

Added a way to allow us specify different kind of schema than EventGridEvent :
- Updated Domain event attribute
- Updated DomainEventWrapper and collection
- Added a cache to be able to retrieve event schema without doing reflection everytime
- Fixed a bug where we were able to publish multiple events of different kinds at once (was not properly supported)
- N/A - Updated the documentation of the project to reflect the changes

Added support for event schema in DomainEvent

---

src/Workleap.DomainEventPropagation.Publishing.ApplicationInsights/ApplicationInsightsPublishingDomainEventBehavior.cs
src/Workleap.DomainEventPropagation.Publishing/TracingPublishingDomainEventBehavior.cs

- Skips ApplicationInsight and Tracing behaviors if publishing CloudEvents
- None

Skipped pipelines if CloudEvent

---

src/Directory.Build.props
src/Workleap.DomainEventPropagation.Publishing/TracingPublishingDomainEventBehavior.cs

We want to apply a code analysis of the latest .NET version used in the project. We can achieve this by adding an analysis level of latest-All.
None, we built the project with the AnalysisLevel and there are no new errors.
Temporarily added property below for testing by building with diagnostics:
```
<ReportAnalyzer>true</ReportAnalyzer>
```

[IDP-510] Set a blanket AnalysisLevel to latest-All

---

src/Shared/DomainEventWrapperCollection.cs
src/Workleap.DomainEventPropagation.Publishing/EventPropagationClient.cs
src/Workleap.DomainEventPropagation.Publishing/EventPropagationPublisherBuilder.cs
src/Workleap.DomainEventPropagation.Subscription.PullDelivery.Tests/CloudEventHandlerUnitTests.cs
src/Workleap.DomainEventPropagation.Subscription.PullDelivery.Tests/EventPullerServiceTests.cs
src/Workleap.DomainEventPropagation.Subscription.PullDelivery.Tests/EventPullerTests.cs
src/Workleap.DomainEventPropagation.Subscription.PullDelivery.Tests/ServiceCollectionEventSubscriptionExtensionsTests.cs
src/Workleap.DomainEventPropagation.Subscription.PullDelivery.Tests/TestExtensions/TaskExtensions.cs
src/Workleap.DomainEventPropagation.Subscription.PullDelivery.Tests/Workleap.DomainEventPropagation.Subscription.PullDelivery.Tests.csproj
src/Workleap.DomainEventPropagation.Subscription.PullDelivery/EventGridClientAdapter/IEventGridClientAdapter.cs
src/Workleap.DomainEventPropagation.Subscription.PullDelivery/EventPropagationSubscriberBuilder.cs
src/Workleap.DomainEventPropagation.Subscription.PullDelivery/EventPullerService.cs
src/Workleap.DomainEventPropagation.Subscription.Tests/Apis/EventsApiIntegrationTests.cs

This is an initial pass at fixing comments for #104.
It mostly consists of:
- cleanup `using` statements
- remove `#pragma warning` when applicable
- rename abstractions, methods, etc
For tests, we've also adapted tests to use xUnit's assertions rather than `FluentAssertions`.

[IDP-902] feat(fix): address initial comments for #104

---

src/Workleap.DomainEventPropagation.Subscription.Tests/Apis/EventsApiIntegrationTests.cs
src/Workleap.DomainEventPropagation.Subscription.Tests/TracingBehaviorTests.cs
src/Workleap.DomainEventPropagation.Subscription.Tests/XunitCollectionConstants.cs

We are running into test flakiness when executing multiple tests in parallel. This is caused by the `InMemoryActivityTracker` being static, so states can leak between test executions. That leak is causing our tests to fail due to flakiness. The solution is run these tests in a sequential fashion as part of a collection.
None.
Verify that tests are no longer flaky.

[IDP-990] Run our tests with Activities sequentially to avoid test flakiness

---

src/Workleap.DomainEventPropagation.Subscription.PullDelivery.Tests/Workleap.DomainEventPropagation.Subscription.PullDelivery.Tests.csproj
src/Workleap.DomainEventPropagation.Subscription.PullDelivery/Workleap.DomainEventPropagation.Subscription.PullDelivery.csproj

`Azure.Identity` at its previous version was flagged as vulnerable when the solution was built.
It was upgraded to its latest version, which is also non-vulnerable.

[IDP-902] deps: use non-vulnerable version for Azure.Identity

---

src/Shared/DomainEventWrapper.cs
src/Shared/DomainEventWrapperCollection.cs
src/Workleap.DomainEventPropagation.Abstractions/DomainEventNameCache.cs
src/Workleap.DomainEventPropagation.Abstractions/DomainEventSchemaCache.cs
src/Workleap.DomainEventPropagation.Abstractions/IEventPropagationClient.cs
src/Workleap.DomainEventPropagation.Publishing.Tests/DomainEventSchemaCacheTests.cs
src/Workleap.DomainEventPropagation.Publishing/EventPropagationClient.cs
src/Workleap.DomainEventPropagation.Subscription.Tests/SampleDomainEvent.cs
src/Workleap.DomainEventPropagation.Subscription.Tests/TracingBehaviorTests.cs

There was a breaking change introduced that required parameterless constructors on some of our interfaces. This caused issues with how DomainEvent could previously be defined as a records.
Given that the changes were not released yet, there should be no breaking changes
Validated with a dev package version that bug was fixed

[IDP-1031] Remove parameterless constructor reqs on interfaces

---

src/Workleap.DomainEventPropagation.Publishing.Tests/EventPropagationClientTests.cs
src/Workleap.DomainEventPropagation.Publishing/EventPropagationClient.cs
src/Workleap.DomainEventPropagation.Subscription.PullDelivery.Tests/PullDeliveryTests.cs
src/Workleap.DomainEventPropagation.Subscription.Tests/Apis/EventsApiIntegrationTests.cs
src/Workleap.DomainEventPropagation.Subscription.Tests/Apis/EventsApiUnitTests.cs
src/Workleap.DomainEventPropagation.Subscription.Tests/DomainEventGridWebhookHandlerTests.cs
src/Workleap.DomainEventPropagation.Subscription.Tests/EventGridRequestHandlerTests.cs
src/Workleap.DomainEventPropagation.Subscription.Tests/PushDeliveryTests.cs
src/Workleap.DomainEventPropagation.Subscription.Tests/Workleap.DomainEventPropagation.Subscription.Tests.csproj
src/Workleap.DomainEventPropagation.Subscription/DomainEventGridWebhookHandler.cs
src/Workleap.DomainEventPropagation.Subscription/EndpointRouteBuilderExtensions.cs
src/Workleap.DomainEventPropagation.Subscription/EventGridRequestHandler.cs
src/Workleap.DomainEventPropagation.Subscription/EventsApi.cs
src/Workleap.DomainEventPropagation.Subscription/IDomainEventGridWebhookHandler.cs
src/Workleap.DomainEventPropagation.Subscription/IEventGridRequestHandler.cs

- Added the capacity to send CloudEvents to a custom EventGrid topic
- Added the capacity to receive CloudEvents through the webhook endpoint
This is backwards compatible

[SGCORE-422] Add support for CloudEvents in Push model

---

src/Workleap.DomainEventPropagation.Publishing/Workleap.DomainEventPropagation.Publishing.csproj

We need to upgrade Azure.Identity away from v1.10.4. This library is implicitly referenced by Microsoft.Extensions.Azure
None that impacts our library.

[IDP-1152] Upgrade Microsoft.Extensions.Azure to v1.7.2

---

src/Workleap.DomainEventPropagation.Publishing/Workleap.DomainEventPropagation.Publishing.csproj
src/Workleap.DomainEventPropagation.Subscription.PullDelivery/Workleap.DomainEventPropagation.Subscription.PullDelivery.csproj

Allow publishing of stable version even when referencing prerelease nuget (necessary given Pull Delivery is still in preview).
None

[IDP-1152] Allow publishing stable version when referencing prerelease

---

README.md
src/Shared/DomainEventMetadataWrapper.cs
src/Shared/DomainEventWrapperCollection.cs
src/Workleap.DomainEventPropagation.Abstractions/IDomainEventMetadata.cs
src/Workleap.DomainEventPropagation.Abstractions/IEventPropagationClient.cs
src/Workleap.DomainEventPropagation.Abstractions/PublicAPI.Shipped.txt
src/Workleap.DomainEventPropagation.Abstractions/PublicAPI.Unshipped.txt
src/Workleap.DomainEventPropagation.Publishing.Tests/EventPropagationClientTests.cs
src/Workleap.DomainEventPropagation.Publishing/EventPropagationClient.cs
src/Workleap.DomainEventPropagation.Publishing/Workleap.DomainEventPropagation.Publishing.csproj

An optional configuration can now be specified when dispatching domain events, allowing to control the CloudEvents metadata fields. EventGridEvents are not supported.
This is only adding an optional parameter, it remains backwards compatible

Adding support to override CloudEvents metadata when publishing an event

---

renovate.json
src/Workleap.DomainEventPropagation.Subscription.PullDelivery.Tests/PullDeliveryTests.cs
src/Workleap.DomainEventPropagation.Subscription.Tests/PushDeliveryTests.cs

Renovate was broken due to depName and currentvalue fields missing.
Local execution
Closes #127

[IDP-1699] Fix renovate for custom.regex on Docker image version in code

---

README.md
src/Workleap.DomainEventPropagation.Publishing.Tests/EventPropagationClientTests.cs
src/Workleap.DomainEventPropagation.Publishing.Tests/ServiceCollectionEventPropagationExtensionsTests.cs
src/Workleap.DomainEventPropagation.Publishing/EventPropagationClient.cs
src/Workleap.DomainEventPropagation.Publishing/EventPropagationPublisherBuilder.cs
src/Workleap.DomainEventPropagation.Publishing/EventPropagationPublisherOptions.cs
src/Workleap.DomainEventPropagation.Publishing/PublicAPI.Shipped.txt

- Add doc to show how to configure EventGridPublisherClientOptions and EventGridClientOptions.
- Changed the internal client names (previously `EventPropagationClient` and `NamespaceTopicClient`) to a public, single name `DomainEventPropagation`
- I search for usage of these strings in our codebases => no results
- It's ok to reuse the same string. .NET named options work per option type AND option name. We already did that in another lib (auditing).
- The Event Grid client names have changed but nobody was refering to them
- The client name is now publicly exposed for people to override the options

[IDP-1715] Improve docs to show how to modify Event Grid client options and expose the client name

---

src/Workleap.DomainEventPropagation.Subscription.PullDelivery.Tests/EventPullerServiceTests.cs
src/Workleap.DomainEventPropagation.Subscription.PullDelivery.Tests/Workleap.DomainEventPropagation.Subscription.PullDelivery.Tests.csproj
src/Workleap.DomainEventPropagation.Subscription.PullDelivery/EventGridClientAdapter/EventGridClientAdapter.cs
src/Workleap.DomainEventPropagation.Subscription.PullDelivery/EventGridClientAdapter/IEventGridClientAdapter.cs
src/Workleap.DomainEventPropagation.Subscription.PullDelivery/EventPropagationSubscriptionOptions.cs
src/Workleap.DomainEventPropagation.Subscription.PullDelivery/EventPullerService.cs
src/Workleap.DomainEventPropagation.Subscription.PullDelivery/PublicAPI.Shipped.txt

A new RetryDelays configuration parameter was added, which gives control over the delays before releasing the lock on failed domain events in Pull Delivery mode.
The tests were also completely rewritten, as dealing with the previous implementation with AutoBogus led to more issues than benefits.
If the new parameter is not set, a default implementation of an exponential backoff is provided. This means that after updating, failed domain events will be released over a progressively longer period time versus before, where they were immediately released.

Adding Configurable Exponential Backoff in Pull Delivery

---

src/Workleap.DomainEventPropagation.Subscription.PullDelivery/EventPullerService.cs

The maximum amount of lock tokens sent per call to Acknowledge, Release or Reject the events is now limited to 100.
While there is no easy to find documentation that states that this is the limit, a comment in the code pointed to this as the limit for the Receive call, and experience has shown that large number of events at once lead to a 400 BadRequest.
Limiting this could lower maximum throughput if more than 100 is supported, but could also enable maximum throughput if that limitation really exists.
There is no breaking change with this.

Limit the amount of events in Ack/Release/Reject calls

---

src/Workleap.DomainEventPropagation.Publishing.Tests/EventPropagationClientTests.cs
src/Workleap.DomainEventPropagation.Publishing/EventPropagationClient.cs
src/Workleap.DomainEventPropagation.Subscription.PullDelivery/EventPullerService.cs

Since the Event Publishing api limits the amount of events received at once at 1000, make sure that whenever we receive more events than the limit we break up the publishing in smaller calls.
Note: There is also technically a size limit (1 MiB) that isn't checked for Cloud Events. Additionally, while the documented limit for Custom Topics is 5000 events, the same limit as Namespace Topics (1000) was also applied for simplicity's sake.
None

Batch event publishing to stay under the limit

---

src/Workleap.DomainEventPropagation.Subscription.PullDelivery.Tests/EventPullerServiceTests.cs
src/Workleap.DomainEventPropagation.Subscription.PullDelivery/EventPullerService.cs

When releasing an event lock in the Pull Delivery mode, it is possible to specify a release delay.
It turns out that the API allows an int, but will only support specific values for that parameter. This PR maps the intended delays to the nearest supported delay by the API, in order to prevent errors.
None

Map the intended delays to the nearest supported delay

---

README.md
src/Shared/LoggingExtensions.cs
src/Workleap.DomainEventPropagation.Publishing/Workleap.DomainEventPropagation.Publishing.csproj
src/Workleap.DomainEventPropagation.Subscription.PullDelivery.Tests/EventPropagationSubscriptionOptionsValidatorTests.cs
src/Workleap.DomainEventPropagation.Subscription.PullDelivery.Tests/EventPullerServiceTests.cs
src/Workleap.DomainEventPropagation.Subscription.PullDelivery/EventPropagationSubscriptionOptions.cs
src/Workleap.DomainEventPropagation.Subscription.PullDelivery/EventPropagationSubscriptionOptionsValidator.cs
src/Workleap.DomainEventPropagation.Subscription.PullDelivery/EventPullerService.cs
src/Workleap.DomainEventPropagation.Subscription.PullDelivery/PublicAPI.Shipped.txt

Add a client side max retries count for the delivery model.
When the delivery attend exceed the max retry configuration it get rejected to be send to the Dead Letter Queues instead of being released.
Not breaking but the behavior has changed: message will be put in DLG instead of being drop.

[IDP-2334] Add client side max retries count for pull delivery

---

.github/workflows/ci.yml
Build.ps1

- Skip nuget push duplicate.
- Setup concurrency option to prevent duplicate run when Renovate falls back to creating a PR

[IDP-2061] Fix auto-merge and nuget conflict

---

.github/workflows/ci.yml
.github/workflows/jira.yml
.github/workflows/publish.yml
.github/workflows/semgrep.yml
README.md
src/Workleap.DomainEventPropagation.Analyzers/AnalyzerReleases.Shipped.md
src/Workleap.DomainEventPropagation.Analyzers/Internals/RuleIdentifiers.cs

TOPS-800: Replacing gsoft-inc/wl-reusable-workflows by workleap/wl-reusable-workflows
--
Not sure why this PR has been created? Reach TechOps in our public slack channel: #techops-and-friends
Some context on the why of this PR can be found here: https://workleap.slack.com/archives/C02E9KPRQ7P/p1737385211295479

hotfix/TOPS-800: Renaming gsoft-inc organization to workleap in github.

---

README.md

Update docs for cloudevents options

Update docs for cloudevents options

---

src/Workleap.DomainEventPropagation.Subscription.PullDelivery.Tests/EventPullerServiceTests.cs
src/Workleap.DomainEventPropagation.Subscription.PullDelivery/EventPullerService.cs

Using Task.WhenAll() will wait until every task is in a completed state before returning. This is problematic when a single subscription crashes, as we would normally expect the exception to bubble up to the IHost and crash it, thus enabling the entire app to be restarted, but it's not happening as long as at least one subscription hasn't crashed out.
This replaces Task.WhenAll() with a system that immediately bubbles up the first exception encountered.
In theory, a pod that was running this background service would survive a crash in a subscription as long as any other subscription didn't crash. With this change, the pod is expected to crash entirely, enabling k8s to detect the broken state and restart it.

Bubble up exceptions happening when handling events

---

src/Directory.Build.props
src/Workleap.DomainEventPropagation.Analyzers.Tests/Workleap.DomainEventPropagation.Analyzers.Tests.csproj
src/Workleap.DomainEventPropagation.Publishing.ApplicationInsights/Workleap.DomainEventPropagation.Publishing.ApplicationInsights.csproj
src/Workleap.DomainEventPropagation.Publishing/Workleap.DomainEventPropagation.Publishing.csproj
src/Workleap.DomainEventPropagation.Subscription.ApplicationInsights/Workleap.DomainEventPropagation.Subscription.ApplicationInsights.csproj
src/Workleap.DomainEventPropagation.Subscription.PullDelivery.Tests/Workleap.DomainEventPropagation.Subscription.PullDelivery.Tests.csproj
src/Workleap.DomainEventPropagation.Subscription.PullDelivery/Workleap.DomainEventPropagation.Subscription.PullDelivery.csproj
src/Workleap.DomainEventPropagation.Subscription.Tests/Workleap.DomainEventPropagation.Subscription.Tests.csproj
src/Workleap.DomainEventPropagation.Subscription/Workleap.DomainEventPropagation.Subscription.csproj

Had to manually bump all packages version. Here's why.
All PRs but one failed due to a vulnerability. This vulnerability update was covered in a PR opened by Dependabot (wtf) and not Renovate. Dependabot's PR was failing Jira branch name, of course.
Instead of dealing with individual PRs, I created a single one to fix everything in one shot.
N/A
Create a patch release after merge.

[IDP-3177] Manually bump version to address Dependabot interference
